# © 2024 Fraunhofer-Gesellschaft e.V., München
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# This configuration file is used by PyCrunch, a PyCharm extension that shows
# pytest coverage in the PyCharm code editor

discovery:
  # some tests should not be considered for the unit test coverage.
  exclusions:
  - test_integration\
engine:
  enable-web-ui: false
  load-pytest-plugins: true
  runtime: pytest
  cpu-cores: 4
pinned-tests: []
