# © 2024 Fraunhofer-Gesellschaft e.V., München
#
# SPDX-License-Identifier: AGPL-3.0-or-later

 name: Extract Python Version
 description: Extracts the Python version from pyproject.toml
 author: Stefan Eidelloth
 runs:
   using: "composite"
   steps:
     - name: Extract Python version from pyproject.toml
       id: python_version
       run: |
         echo "foo"