# © 2024 Fraunhofer-Gesellschaft e.V., München
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: doc

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:    
  doc:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: ./extract-python-version
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install python dependencies
        run: |   
          # also see settings in pyproject.toml
          pip install .[doc]  | grep -v 'already satisfied' # The grep part removes "already satisfied" messages from the pip3 install output on linux systems        
      - name: build html doc
        run: |
          cd doc
          make html
      - name: install latex
        run: |          
          sudo apt-get update -y || true
          sudo apt-get install -y latexmk
          sudo apt-get install -y texlive-latex-extra  # otherwise LaTeX Error: File `cmap.sty' not found
          # for possible required latex packages also see
          # https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.latex.LaTeXBuilder
          # sudo apt-get install -y texlive-latex-recommended
          # sudo apt-get install -y texlive-fonts-recommended
      - name: build pdf doc
        run: |
          cd doc
          make latexpdf
      - name: setup github pages
        uses: actions/configure-pages@v5
      - name: pages artifact
        uses: actions/upload-pages-artifact@v3
        with:              
          path: 'doc/build/html'
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: deploy to web server
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_URL }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: './doc/build/html'
          remoteDir: './doc'
          reverse: true   
