name: doc_pdf

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:    
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: install python dependencies
        run: |
          cd back_end       
          # also see settings in pyproject.toml
          pip install .[doc]  | grep -v 'already satisfied' # The grep part removes "already satisfied" messages from the pip3 install output on linux systems
      - name: install latex
        run: |
          apt-get update -y 
          apt-get install -y latexmk 
          # apt-get install -y texlive-latex-recommended 
          # apt-get install -y texlive-latex-extra 
          # apt-get install -y texlive-fonts-recommended
      - name: build doc
        run: |
          cd doc
          make latexpdf
      - name: setup github pages
        uses: actions/configure-pages@v3
      - name: pages artifact
        uses: actions/upload-pages-artifact@v2
        with:              
          path: 'doc/build/html'
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v2
