name: doc_pdf

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:    
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: install dependencies
        run: |
          cd back_end       
          # also see settings in pyproject.toml
          pip install .[doc]  | grep -v 'already satisfied' # The grep part removes "already satisfied" messages from the pip3 install output on linux systems        
      - name: build pdf doc
        uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: 'apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended'
          build-command: 'make latexpdf'
          docs-folder: 'doc/'
      - name: setup github pages
        uses: actions/configure-pages@v3
      - name: pages artifact
        uses: actions/upload-pages-artifact@v2
        with:              
          path: 'doc/build/html'
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v2
