# This workflow will install Python dependencies and build the spinx documentation
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: install dependencies
      run: |
        cd back_end       
        # also see settings in pyproject.toml
        pip install .[dev]  | grep -v 'already satisfied' # The grep part removes "already satisfied" messages from the pip3 install output on linux systems        
    - name: build
      run: |
        cd doc
        make html
        make pdf     
     name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: doc
          path: |
            doc/build           