# This workflow installs Python dependencies and uses the reuse tool
# to confirm reuse compliance
# For more information see: https://reuse.software/

name: reuse_compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: reuse compliance check
        uses: fsfe/reuse-action@v2